packages:
  - apps/*
  - packages/*

ignoredBuiltDependencies:
  - esbuild

onlyBuiltDependencies:
  - '@nestjs/core'
  - '@openapitools/openapi-generator-cli'
  - '@prisma/client'
  - '@prisma/engines'
  - prisma
